version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      # - ./docker/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
